Repository SpongePowered/SpongeDocs, pull requests merged in 2018-07, with the labels that each got.

#711 Update example of PermissionDescription: fix #710
  source/plugin/permissions.rst
Labels: outdated docs

#709 Elaborate on Ore Naming Guidelines
  source/ore/guidelines.rst
Labels: Ore

#717 Fix remaining types of code blocks
  source/about/tos.rst
  source/contributing/howtogit.rst
  source/contributing/implementation/datamanipulator.rst
  source/contributing/implementation/pr.rst
  source/contributing/spongedocs.rst
  source/plugin/configuration/nodes.rst
  source/plugin/practices/bad.rst
  source/plugin/wgen/modifiers.rst
  source/preparing/git.rst
  source/server/getting-started/configuration/hocon.rst
  source/server/getting-started/configuration/sponge-conf.rst
  source/server/getting-started/launch-script.rst
  source/server/management/exploit-patches.rst
  source/server/management/performance-tweaks.rst
Labels: input wanted

#720 Show outdated warning - Fixes #719
  source/about/assets.rst
  source/about/faq.rst
  source/about/future.rst
  source/about/glossary.rst
  source/about/index.rst
  source/about/introduction.rst
  source/about/license.rst
  source/about/posting.rst
  source/about/rules.rst
  source/about/staff.rst
  source/about/structure.rst
  source/contributing/guidelines.rst
  source/contributing/implementation/codestyle.rst
  source/contributing/implementation/index.rst
  source/contributing/implementation/pr.rst
  source/contributing/index.rst
  source/contributing/spongedocs.rst
  source/index.rst
  source/ore/guidelines.rst
Labels: Ore, low priority, outdated docs

#725 Improving documentation for getting started with IDEA.
  source/plugin/workspace/idea.rst
Labels: needs review
