Repository SpongePowered/SpongeDocs, pull requests merged in 2018-11, with the labels that each got.

#771 Fix outdated causes in economy practices
  source/plugin/economy/practices.rst
Labels: low priority, needs review, outdated docs

#766 Extend plugin configuration docs. Fixes #735. Fixes #553
  source/plugin/configuration/index.rst
  source/plugin/configuration/loaders.rst
  source/plugin/configuration/nodes.rst
  source/plugin/configuration/serialization.rst
Labels: input wanted, low priority, needs review

#754 Add tools for maintaining the docs
  .gitignore
  source/contributing/implementation/datamanipulator.rst
  source/plugin/commands/creating.rst
  source/plugin/data/custom/serialization.rst
  source/plugin/entities/ai.rst
  source/plugin/injection.rst
  source/plugin/items/creating.rst
  source/plugin/ray-tracing.rst
  source/plugin/services.rst
  tools/.gitignore
  tools/README.md
  tools/code-checker/LICENSE.txt
  tools/code-checker/README.md
  tools/code-checker/pom.xml
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/FileChecker.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/JavaFileWriter.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/KeywordBasedDeIndenter.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/KeywordPartitioner.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/KeywordRedirectingPredicate.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/Main.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/OnOffKeywordPredicate.java
  tools/code-checker/src/main/java/org/spongepowered/docs/tools/codeblock/RepeatedKeywordPredicate.java
  tools/code-checker/src/main/resources/java-support/Utils.java
  tools/code-checker/src/main/resources/log4j2.xml
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/FileCheckerTest.java
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/KeywordBasedDeIndenterTest.java
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/KeywordPartitionerTest.java
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/KeywordRedirectingPredicateTest.java
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/OnOffKeywordPredicateTest.java
  tools/code-checker/src/test/java/org/spongepowered/docs/tools/codeblock/RepeatedKeywordPredicateTest.java
  tools/code-checker/src/test/resources/Code_TestFile.java
  tools/code-checker/src/test/resources/TestFile.rst
  tools/javadoc-checker/LICENSE.txt
  tools/javadoc-checker/README.md
  tools/javadoc-checker/pom.xml
  tools/javadoc-checker/src/main/java/org/spongepowered/docs/tools/javadoc/ClassUtils.java
  tools/javadoc-checker/src/main/java/org/spongepowered/docs/tools/javadoc/FileChecker.java
  tools/javadoc-checker/src/main/java/org/spongepowered/docs/tools/javadoc/Main.java
  tools/javadoc-checker/src/main/resources/log4j2.xml
Labels: meta, needs review

#763 Preliminary guidelines update for 7.1.0
  source/ore/guidelines.rst
Labels: Ore
