Repository SpongePowered/SpongeDocs, pull requests merged in 2018-08, with the labels that each got.

#730 Mention signature download url. Fixes #612
  source/ore/routes/download.rst
Labels: Ore

#729 Add note regarding API major version changes. Fixes #630
  source/server/management/plugins.rst
Labels: low priority

#733 Mention command features. Fixes #502
  source/images/command-features.png
  source/server/spongineer/commands.rst
Labels: input wanted, low priority, needs review

#734 Use absolute paths instead of relative paths that go through root
  source/about/faq.rst
  source/contributing/guidelines.rst
  source/contributing/howtogit.rst
  source/contributing/implementation/codestyle.rst
  source/contributing/implementation/datamanipulator.rst
  source/contributing/index.rst
  source/plugin/configuration/index.rst
  source/plugin/permissions.rst
  source/server/getting-started/configuration/server-properties.rst
  source/server/getting-started/configuration/sponge-conf.rst
  source/server/management/permissions.rst
  source/server/management/whitelist.rst
  source/server/spongineer/commands.rst
  source/server/spongineer/troubleshooting.rst
Labels: low priority

#736 Document catalog types. Fixes #185.
  source/plugin/data/catalog-types.rst
  source/plugin/data/index.rst
Labels: low priority

#739 Document changed multi-world-behaviour. Fixes #505
  source/server/spongineer/commands.rst
Labels: low priority

#738 Add a note about thread safety. Fixes #242.
  source/plugin/permissions.rst
Labels: low priority, needs review

#742 s/Web Development/Web Developer
  source/about/staff.rst
Labels: low priority

#737 Add a note that item stacks are usually just a copy. Fixes #334
  source/plugin/items/usage.rst
Labels: input wanted, low priority

#745 Add pretty printed exception example + steps to analyze. Fixes #479
  source/server/spongineer/debugging.rst
Labels: low priority

#732 Convert global.conf table to dictionary list
  source/server/getting-started/configuration/sponge-conf.rst
Labels: FLARD, input wanted

#747 Document missing commands and permissions.
  source/server/spongineer/commands.rst
Labels: low priority, needs review, outdated docs

#751 Update references to the closed bungeecord PRs for SpongeForge support
  source/server/getting-started/bungeecord.rst
Labels: low priority

#749 Document regex und selector support in CommandElements
  source/plugin/commands/arguments.rst
  source/plugin/commands/index.rst
Labels: low priority

#750 Add guidance on appropriate choice of version number for new plugins
  source/plugin/project/gradle.rst
  source/plugin/project/index.rst
  source/plugin/project/maven.rst
  source/plugin/project/version-numbers.rst
  source/plugin/workspace/eclipse.rst
  source/plugin/workspace/idea.rst
Labels: input wanted, low priority

#756 Update mixins page. Fixes #752
  source/plugin/internals/mixins.rst
Labels: low priority, outdated docs
