Repository SpongePowered/SpongeDocs, pull requests merged in 2018-02, with the labels that each got.

#655 Updated Ray Tracing according to issue #653
  source/plugin/ray-tracing.rst
Labels: outdated docs

#662 Cleanup Issue Reporting Info
  source/server/spongineer/bugreport.rst
Labels: outdated docs

#656 Update the event cause page for API 7
  source/plugin/event/causes.rst
Labels: outdated docs

#643 Mixin does allow lambdas and method references.
  source/contributing/implementation/mixins.rst
Labels: factual error, outdated docs

#580 Plugin Meta stuff
  source/plugin/plugin-class.rst
  source/plugin/plugin-meta.rst
Labels: FLARD

#638 Update Effects page
  source/plugin/effects.rst
Labels: needs review

#654 Fix and update plugin/blocks pages
  source/plugin/blocks/accessing.rst
  source/plugin/blocks/modifying.rst
Labels: needs review, outdated docs
