Repository SpongePowered/SpongeDocs, pull requests merged in 2018-09, with the labels that each got.

#761 Document the entity and block meta data display requirements. Fixes #584
  source/server/spongineer/commands.rst
Labels: input wanted, low priority, needs review

#746 Update MCP page. Fixes #743
  source/plugin/internals/mcp-setup.rst
Labels: low priority

#753 more debugging clarifications and rewrites
  source/server/spongineer/debugging.rst
Labels: input wanted, low priority

#755 Start working on the metrics collection docs.
  source/plugin/index.rst
  source/plugin/metrics.rst
  source/server/getting-started/configuration/sponge-conf.rst
  source/server/spongineer/commands.rst
Labels: Ore

#765 Update version references to 7.1.0
  source/conf.py
  source/ore/routes/deploy-version.rst
  source/ore/routes/list-versions.rst
  source/ore/routes/project-version.rst
  source/ore/routes/project.rst
  source/plugin/internals/implementation.rst
  source/plugin/internals/mcp-setup.rst
  source/plugin/project/gradle.rst
  source/plugin/project/index.rst
  source/plugin/project/maven.rst
  source/server/getting-started/configuration/sponge-conf.rst
  source/server/getting-started/implementations/spongeforge.rst
Labels: high priority

#764 Document API-Versions - Fixes #652. Fixes #585
  source/plugin/api-versions.rst
  source/plugin/index.rst
  source/plugin/internals/mcp-setup.rst
  source/server/getting-started/implementations/spongeforge.rst
Labels: input wanted
