Repository SpongePowered/SpongeDocs, pull requests merged in 2018-10, with the labels that each got.

#741 Document Entity AI
  source/images/ai-execution-order.dot
  source/images/ai-execution-order.png
  source/plugin/entities/ai.rst
  source/plugin/entities/custom-ai.rst
  source/plugin/entities/index.rst
Labels: low priority

#770 Fixed some typos
  source/plugin/project/version-numbers.rst
Labels: low priority, needs review

#760 The tasks won't stop unless they are told to. Fixes #480
  source/plugin/scheduler.rst
Labels: low priority, needs review

#769 Register WorldGenerarorModifier with new API
  source/plugin/wgen/modifiers.rst
Labels: needs review, outdated docs
