Repository SpongePowered/SpongeDocs, pull requests merged in 2023-04, with the labels that each got.

#954 npm update dependencies
  package-lock.json
Labels: dependencies

#950 Staff Update 2023 A
  source/about/staff.rst
Labels: outdated docs

#957 Updated mods list
  source/server/spongineer/incompatible.rst
Labels: needs review, outdated docs
